// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeS1wOpwuhFnBdtEZaIkVzcRECVqja7Q',
    appId: '1:1055547025451:android:9878fdb3bb9a615331626e',
    messagingSenderId: '1055547025451',
    projectId: 'azurite-2ff57',
    storageBucket: 'azurite-2ff57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIluz_cifHYdOpotn5zF357ueTbZaV8w',
    appId: '1:1055547025451:ios:52b180f21a9fb3fb31626e',
    messagingSenderId: '1055547025451',
    projectId: 'azurite-2ff57',
    storageBucket: 'azurite-2ff57.firebasestorage.app',
    androidClientId: '1055547025451-i6e9l3roe63hp44vmjrg9js8p0qo1gts.apps.googleusercontent.com',
    iosClientId: '1055547025451-1abf47orfpg4pgsb7f3qkuob4372jr4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.azurite',
  );

}